CREATE TABLE Player(
    ID INTEGER NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Age INTEGER NOT NULL,
    Nationality VARCHAR(30) NOT NULL,
    Dob TIMESTAMP,
    Designation INTEGER,
    PRIMARY KEY(ID)
);

